//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaAppEntities1 : DbContext
    {
        public CinemaAppEntities1()
            : base("name=CinemaAppEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CountriesFilm> CountriesFilms { get; set; }
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<FilmsGenre> FilmsGenres { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Hall> Halls { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Poster> Posters { get; set; }
        public virtual DbSet<Seat> Seats { get; set; }
    }
}
