//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> PosterId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> SeatId { get; set; }
        public Nullable<int> Column { get; set; }
    
        public virtual Poster Poster { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
